### PR TITLE
Add rocket suite with parameters.

### PR DESCRIPTION
**Pull request by hjoliver**
Even though the rocket suite has non-trivial Jinja2 loops (over partial ranges) it can be done with parameters. I'm not sure I'd suggest replacing the original (although I would if it was a more straightforward suite with simple loops), but it might be instructive to include both?

### CODE REVIEW

**Comment by oliver-sanders** [comment]
Perhaps we could use this suite for a parametrised task advanced tutorial?

It would be good to sell this new feature.

**Comment by hjoliver** [comment]
I'd be happy with that.

Given the interest of attendees in multi-run climate experiments, I wonder if we should also add a small example of Jinja2 vs parameters somewhere, to make it really clear at glance?   Maybe something as simple as this (omitting non-essential bits here):

```
{% for MEM in range(5) %}
     pre => sim_{{MEM}} => post
{% endfor %}
```

vs

```
   pre => sim<MEM> => post
```

(however, if you think we've run out of time to make changes, I'll let it slide)

**Comment by oliver-sanders** [comment]
Could probably cover the topic quite quickly, your example is pretty simple to understand.

**Comment by hjoliver** [comment]
Sorry, getting late here, I forgot there is also the simple Jinja2 example in the "advanced" sections, which I commented on here:

https://github.com/oliver-sanders/cylc-tutorial/pull/4#issuecomment-246216755

Maybe just show the parameterized version of this as well.

**Comment by hjoliver** [comment]
(previous comment addressed by #7)

**Pull request merged**
