### PR TITLE
Add complex demo suite

### PR DESCRIPTION
**Pull request by benfitzpatrick**
This is an example put together by @oliver-sanders with a bit of finishing by me.

@hjoliver, please review.

### CODE REVIEW

**Comment by hjoliver** [comment]
Whoa, pretty spectacular.

This should be pretty impressive if it runs well - I presume you've checked that it does, on a demo laptop?

Better not have the graph view shown by default in the VMs - the graphviz dot program eats CPU and takes a minute or more to lay out the ungrouped graph

Some of the graph strings are not very tidy (inconsistent use of whitespace etc.) - but I suppose that's a minor point.

If there is potential for this to bring a user's laptop to its knees, should it just be on loaded on your demo machine and not the tutorial VM?  (in which case, maybe the VM could have another suite that is big enough to be impressive without being too big?).

But maybe you don't have performance concerns?  I'll have more of a play later, gotta go out for an hour or two now...

**Comment by hjoliver** [comment]
Wow, but the ungrouped graph does look really frightening!

**Comment by benfitzpatrick** [comment]
I think the VM performance _should_ be OK on one of our nicer MO laptops unless we do a connected ungrouped Graph View. I haven't included any reference to this suite in the tutorial so that we can control a bit how people see it - I am hoping we can give some caveats before they try it.

**Comment by benfitzpatrick** [comment]
The whole suite is a hacked suite.rc.processed, so it is a bit jumbly.

**Pull request merged**
